### ISSUE TITLE
adding ID to route

### ISSUE THREAD

**Issue by illuminate3** [caffeinated/menus#1]
hmmm, this doesn't seem possible.

```
->add('view profile', 'profiles'. Auth::user()->id )
```

Or am I doing something wrong again?

**Comment by kaidesu** [comment]
There's a few quirks I'm working out, so I wouldn't be surprised if its a legit bug right now.

Also, looks like you need a trailing slash after `profiles`?

``` php
use Auth;
use Menu;

...

Menu::make('example', function($menu)) {
    $menu->add('View Profile', 'profiles/'.Auth::user()->id);
});
```

And be sure to check if you're logged in first, otherwise `Auth::user()` will return `null`.

**Comment by illuminate3** [comment]
@bugs
figured as much, however, this package is another of yours I'm all over :smile: 

@error
I have the Auth::user()->id displaying on the same page, so not a null situation.

```
<?php namespace App\Providers;

use Illuminate\Support\ServiceProvider;

use Auth;
use Menu;

class MenuServiceProvider extends ServiceProvider {

    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        Menu::make('public', function($menu) {
            $menu->add('Rakko', 'welcome');
            $menu->add('Profiles', 'profiles');
//          $menu->add('View Profile', 'profiles/'.Auth::user()->id);
//          $menu->add('view profile', 'profiles'. Auth::user()->id );
        });
    }
```

I don't have a register method.

Error:

```
Trying to get property of non-object
```

**Comment by kaidesu** [comment]
I'll be sure to look into this!

**Comment by kaidesu** [comment]
I believe this is simply due to the loading order of service providers. If you die and dump the result of `Auth::user()` you'll find that it is `null` (thus, the `Trying to get property of non-object` error). The session data is not loaded until _after_ all service providers have booted.

See the following forum threads for more information:
- http://laravel.io/forum/12-17-2014-session-content-not-available-in-service-providers-register
- https://laracasts.com/discuss/channels/general-discussion/laravel-5-session-data-is-not-accessible-in-the-app-boot-process
- https://laracasts.com/discuss/channels/general-discussion/how-do-i-get-the-current-authenticated-user-laravel-5

**Comment by IndraGunawan** [comment]
What is the solution for this problem?
