### ISSUE TITLE
using shinobi with menus

### ISSUE THREAD

**Issue by illuminate3** [caffeinated/menus#17]
in my MenuServiceProvider I tried:

```
    public function boot()
    {

// navbar menu
        if ( (Auth::user()->can('manage_admin')) || (Auth::user()->can('manage_shisan')) ) {
        $menu = Menu::get('navbar');
...
}}
```

and end up with the error:

```
Call to a member function can() on a non-object
```

I was wondering if there is a way to prevent menus from showing based on user permissions.

arigatou~~~!

**Comment by kaidesu** [comment]
Nothing baked in.

You can check from your view files though easily enough, I would think. Can utilize the `data()` method to add permissions to each item, and then you can run a check for them within blade to echo out the link or not. Not the most performance-conscious solution though (simply due to Shinobi not caching permissions, so every time you fire the `can()` method, it goes out and hits your database and returns the results), but shouldn't be a problem if you don't have a lot of menu items.
