### ISSUE TITLE
Generate sub-items for item with an image

### ISSUE THREAD

**Issue by myrrc** [caffeinated/menus#39]
Hello. I generate the item which contains only <img> tag. Is there a possibility to add subitems for such?
![2015-05-25 23-30-46](https://cloud.githubusercontent.com/assets/7099650/7801972/7fcbd642-033e-11e5-875a-5fcd6172a2f8.png)

**Comment by kaidesu** [comment]
It'd be better to simply assign that menu item a class, where in your CSS you would set the `color` to `transparent` and assign your background image. This way you're not hardcoding HTML within your menu instance.

Otherwise, every item is assigned a unique ID number on top of the slug. You can `dd` your `$menu` instance and see what ID that menu item is being assigned.

Read more here: https://github.com/caffeinated/menus/wiki/Basics-of-Menu-Items

**Comment by myrrc** [comment]
Thanks
